#!/usr/bin/env python3

import os
import yaml
from src.clicksquid import ClickSquid

script_dir = os.path.dirname(os.path.realpath(__file__))
config_file_path = os.path.join(script_dir, 'config.yaml')
error_file_path = os.path.join(script_dir, 'logs/error.log')
config_file = open(config_file_path, 'r')
config = yaml.load(config_file, Loader=yaml.FullLoader)
    
app = ClickSquid(config, error_file_path)
app.run() 